# ! [ doc = "Peripheral access API for LPC176X5X microcontrollers (generated using svd2rust v0.9.1)\n\nYou can find an overview of the API [here].\n\n[here]: https://docs.rs/svd2rust/0.9.1/svd2rust/#peripheral-api" ] # ! [ deny ( missing_docs ) ] # ! [ deny ( warnings ) ] # ! [ allow ( non_camel_case_types ) ] # ! [ feature ( const_fn ) ] # ! [ feature ( optin_builtin_traits ) ] # ! [ no_std ]extern crate cortex_m ;

extern crate vcell ;

pub use cortex_m::peripheral::Cpuid as CPUID;
pub use cortex_m::peripheral::CPUID;
pub use cortex_m::peripheral::Dcb as DCB;
pub use cortex_m::peripheral::DCB;
pub use cortex_m::peripheral::Dwt as DWT;
pub use cortex_m::peripheral::DWT;
pub use cortex_m::peripheral::Fpb as FPB;
pub use cortex_m::peripheral::FPB;
pub use cortex_m::peripheral::Fpu as FPU;
pub use cortex_m::peripheral::FPU;
pub use cortex_m::peripheral::Itm as ITM;
pub use cortex_m::peripheral::ITM;
pub use cortex_m::peripheral::Mpu as MPU;
pub use cortex_m::peripheral::MPU;
pub use cortex_m::peripheral::Nvic as NVIC;
pub use cortex_m::peripheral::NVIC;
pub use cortex_m::peripheral::Scb as SCB;
pub use cortex_m::peripheral::SCB;
pub use cortex_m::peripheral::Syst as SYST;
pub use cortex_m::peripheral::SYST;
pub use cortex_m::peripheral::Tpiu as TPIU;
pub use cortex_m::peripheral::TPIU;

pub mod interrupt;
pub mod wdt;
pub mod timer;
pub mod uart;
pub mod uart1;
pub mod pwm;
pub mod i2c;
pub mod spi;
pub mod rtc;
pub mod gpioint;
pub mod pinconnect;
pub mod ssp;
pub mod adc;
pub mod canafram;
pub mod canaf;
pub mod ccan;
pub mod can;
pub mod dac;
pub mod i2s;
pub mod rit;
pub mod mcpwm;
pub mod qei;
pub mod syscon;
pub mod emac;
pub mod gpdma;
pub mod usb;
pub mod gpio;
